---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuexiao.
--- DateTime: 2022/2/22 下午10:16
--- 限流计数器脚本，负责完成访问计数和限流结果判断。该脚本需要在Redis中加载和执行

-- 返回0表示需要限流，返回其他值表示访问次数

local cacheKey = KEYS[1];
local data = redis.call("incr", cacheKey);
local count = tonumber(data);

-- 首次访问，设置过期时间
if count == 1 then
    redis.call("expire", cacheKey, 10);
end

if count > 10 then
    return 0;    -- 0表示需要限流
end

return count;

